### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Zhengyan1224** [qian-o/SabaSharp#5]
你好，直接运行项目会报加载pmx模型时顶点集合空指针，是为什么呢？
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Saba.PmxModel.Load(String path, String mmdDataDir) in D:\Project\CSharp\SabaSharp-master\Saba\PmxModel.cs:line 297
   at SabaViewer.MikuMikuDance.LoadModel(String modelPath, String vmdPath) in D:\Project\CSharp\SabaSharp-master\SabaViewer\MikuMikuDance.cs:line 395   
   at SabaViewer.MikuMikuDance..ctor(GL gl, String modelPath, String vmdPath) in D:\Project\CSharp\SabaSharp-master\SabaViewer\MikuMikuDance.cs:line 68 
   at SabaViewer.Scene1.Load() in D:\Project\CSharp\SabaSharp-master\SabaViewer\Scene1.cs:line 20
   at SabaViewer.Contracts.Game.<.ctor>b__30_0() in D:\Project\CSharp\SabaSharp-master\SabaViewer\Contracts\Game.cs:line 69
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at SabaViewer.Contracts.Game.Run() in D:\Project\CSharp\SabaSharp-master\SabaViewer\Contracts\Game.cs:line 178
   at Program.Main(String[] args) in D:\Project\CSharp\SabaSharp-master\SabaViewer\Program.cs:line 11`

**Comment by qian-o** [comment]
可以在报错的代码截下图吗？

**Comment by Zhengyan1224** [comment]
![微信截图_20240325173325](https://github.com/qian-o/SabaSharp/assets/9921746/77b90c91-ebee-4452-8185-83cf75f02f27)
在这里给FixedArray<Vector3>类型的模型顶点赋值的时候

**Comment by qian-o** [comment]
在创建FixedArray时，按理来说不会存在null的情况，如果是抛异常的话也不会往下继续执行。可以断点调试下吗？
![image](https://github.com/qian-o/SabaSharp/assets/84434846/81389c9b-4fea-4fad-b57b-4b2960ed1ed2)
![image](https://github.com/qian-o/SabaSharp/assets/84434846/7a139129-b4a5-4fda-8d86-9b024d717ea7)

**Comment by Zhengyan1224** [comment]
![1711364801618](https://github.com/qian-o/SabaSharp/assets/9921746/ede61375-ba5f-4d71-bc2a-2f4a28427804)
![1711364856386](https://github.com/qian-o/SabaSharp/assets/9921746/ec658359-dad7-4d2f-bb72-423cad7cbc69)
FixedArray对象应该是有正常创建，但是获取FixedArray的元素的时候报空指针，感觉应该是分配非托管堆的时候有问题，不知道我的理解对不对

**Comment by qian-o** [comment]
看样子内存分配失败了，.net内置的分配应该不会出问题。可能是通过opencl分配的有问题。
![image](https://github.com/qian-o/SabaSharp/assets/84434846/339c49de-37b0-4a91-ad5e-2c5164680fbe)
这块先注掉再试试呢。

**Comment by Zhengyan1224** [comment]
注释完可以了，谢谢大佬。对了OpenCL分配失败会不会是我电脑显卡驱动的问题？

**Comment by qian-o** [comment]
跟驱动没关系，可能硬件不支持svm内存，这地方我检测的不够完善。方便的话可以提供下显卡型号吗？

**Comment by Zhengyan1224** [comment]
我是核显/(ㄒoㄒ)/~~

**Comment by qian-o** [comment]
好吧，那这个 issues 就先关掉了。
